export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UI_SHOW_ERROR = 'UI_SHOW_ERROR';
export const UI_RESET_ERROR = 'UI_RESET_ERROR';
export const LOADER_REQUEST = 'LOADER_REQUEST';
export const LOADER_SUCCESS = 'LOADER_SUCCESS';

export const ADS_LOADED_SUCCESS = 'ADS_LOADED_SUCCESS';
export const CLEAR_ADVERTS = 'CLEAR_ADVERTS';

export const SINGLE_LOADED_SUCCESS = 'SINGLE_LOADED_SUCCESS';
export const SINGLE_LOADED_FAILED = 'SINGLE_LOADED_FAILED';

export const COLLECTED_TAGS = 'COLLECTED_TAGS';
