export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UI_SHOW_ERROR = 'UI_SHOW_ERROR';
export const UI_RESET_ERROR = 'UI_RESET_ERROR';

export const ADS_LOADED_SUCCESS = 'ADS_LOADED_SUCCESS';

export const SINGLE_LOADED_SUCCESS = 'SINGLE_LOADED_SUCCESS';
export const SINGLE_LOADED_FAILED = 'SINGLE_LOADED_FAILED';
export const DELETE_SINGLE = 'DELETE_SINGLE';
